hardware/src/it/java/org/sentrysoftware/metricshub/hardware/it/SuperConnectorOsIT.java
hardware/src/it/resources/os/SuperConnectorOsIT/connectors/SuperConnectorCommon-header/SuperConnectorCommon-header.yaml
hardware/src/it/resources/os/SuperConnectorOsIT/expected/expected.json
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/common/helpers/MetricsHubConstants.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/utils/MappingProcessor.java
metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/utils/MappingProcessorTest.java

* Adjusted the concatenation in the MappingProcessor to invoke the concatenateColumnsValue method.
* Implement relevant test cases to reflect the corrected behavior.

Issue  #10: support concatenation in yaml connectors for attribute mapping

---

pom.xml

* Update clients versions (tablejoin, snmp, wmi, http, wbem, ipmi, ssh, jflat, xflat, winrm, vcenter) from **1.0.00** to **1.0.01**

Issue #11: Fix unsupported operation

---

metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/service/MetricsHubCliService.java

* Add connector categories to CLI when the connectors are listed
* Fix potential bug when connectorName is displayed

Issue #31: Display connector categories in cli list

---

metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/collect/ProtocolHealthCheckStrategy.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/detection/DetectionStrategy.java
metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/collect/ProtocolHealthCheckStrategyTest.java
metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/detection/DetectionStrategyTest.java

* Developped SSH protocol health check
* Created a test case for SSH protocol health check
* Tested SSH protocol health check on metricshub with the agent

Issue #18: Ssh Protocol Check Metric

---

metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/collect/ProtocolHealthCheckStrategy.java
metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/collect/ProtocolHealthCheckStrategyTest.java

* Developped IPMI protocol health check
* Created a test case for IPMI protocol health check
* Tested IPMI protocol health check on metricshub with the agent

Issue #18: Ipmi protocol check metric

---

.github/workflows/build.yml

Fixed Linux package path in the `Upload Linux Artifact` step.

Issue #52: Fix Linux artifcat generated by the GitHub Build Action

---

.github/workflows/maven-build.yml
.github/workflows/maven-deploy.yaml
.github/workflows/maven-deploy.yml
.github/workflows/maven-release.yml
README.md
metricshub-doc/src/site/markdown/install.md
metricshub-linux/pom.xml
metricshub-windows/pom.xml
pom.xml

* Created maven release workflow
* Created maven deploy workflow
* Updated POM files to manage Maven Central deployments

Issue #55: Create release workflow

---

metricshub-doc/src/site/markdown/troubleshooting/cli.md

Wrap connectors option using double quotes in documentation

Issue #77: Wrap connectors option using double quotes in doc

---

metricshub-doc/src/site/markdown/concepts.md
metricshub-doc/src/site/markdown/glossary.md
metricshub-doc/src/site/markdown/index.md
metricshub-doc/src/site/markdown/security/security.md
metricshub-doc/src/site/markdown/start.md
metricshub-doc/src/site/markdown/usecases/custom.md
metricshub-doc/src/site/markdown/usecases/sustainability.md
metricshub-doc/src/site/site.xml

1st version submitted to @NassimBtk  for merging

Issue #6: Review user documentation

---

metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/service/MetricsHubCliService.java

* Inversed instructions order for the sake of optimization and enhancement.
* Tested and approved

Issue #85: Enhance MetricsHub CLI performance

---

metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/service/protocol/SnmpConfigCli.java

* Remove snmpV3 references from SnmpConfigCli

Issue #106: Remove remaining snmpV3 references

---

metricshub-doc/src/site/markdown/troubleshooting/solving.md
metricshub-doc/src/site/site.xml

* Listed error in documentation

Issue #57: document metricslogs export failure

---

pom.xml

* Added `community-connectors.version` maven property

Issue #129: Fixed `metricshub_agent_info` community connector version

---

metricshub-doc/src/site/markdown/configuration/configure-agent.md

* added the required info in configure-agent.md

Issue #137: Documented custom resource monitoring

---

metricshub-doc/src/site/markdown/configuration/configure-agent.md

Issue #144: Fixed bug in configure-agent.md

---

metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/utils/MappingProcessor.java
metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/utils/MappingProcessorTest.java

Added support for millivolt2volt function

Issue #111: Added support for millivolt2volt function

---

.github/dependabot.yml
pom.xml

Issue #118: Set dependencies versions inline instead of properties in pom.xml

---

metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/service/MetricsHubCliService.java

Added tryInteractiveSnmpV3Password method

Issue 199#:  Implement an interactive mode for SNMP V3 password entry

---

README.md
metricshub-doc/src/site/markdown/configuration/configure-agent.md
metricshub-linux/src/main/resources/jpackage/metricshub/config/metricshub-example.yaml
metricshub-windows/src/main/resources/jpackage/MetricsHub/config/metricshub-example.yaml

* Added documentation for ping extension

Issue #196: Develop a Ping Extension

---

metricshub-doc/src/site/markdown/configuration/configure-agent.md

* Added a note in the configure-agent.md

Issue 104: Document environment variables

---

metricshub-doc/pom.xml
pom.xml

* Updated dependency versions in `metricshub-doc/pom.xml` and `/pom.xml`

Issue #219: Use C. Connectors v1.0.04 and Connector Maven Plugin v1.0.03

---

metricshub-agent/src/main/resources/metricshub-host-metrics.yaml
metricshub-doc/src/site/markdown/getting-started-linux.md
metricshub-doc/src/site/markdown/getting-started-windows.md

Updated getting-started-windows.md and getting-started-linux.md

Issue #223: Update Prometheus Configuration for Windows and Linux Getting Started

---

README.md
metricshub-doc/src/site/markdown/develop/connector.md
metricshub-doc/src/site/markdown/develop/sources/sql.md
metricshub-doc/src/site/site.xml

Added documentation for SQL Source and added module entry in README

Issue #230: Document SQL Source and add module entry in README

---

metricshub-agent/src/main/resources/metricshub-host-metrics.yaml

Updated metricshub-host-metrics.yaml

Issue #231: Add hw.status metric definition to metricshub-host-metrics.yaml

---

metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/parser/ReferenceResolverProcessor.java
metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/connector/parser/ReferenceResolverProcessorTest.java

Correction of the regex for Source references to handle Pre Sources

Issue #233: Pre Sources are not referenced correctly

---

metricshub-oscommand-extension/src/main/java/org/sentrysoftware/metricshub/extension/oscommand/OsCommandRequestExecutor.java

* Updated `OsCommandRequestExecutor` to remove remote files using `SshClient#removeFile`

Issue #248: Removes remote files after SSH command execution

---

metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/common/helpers/LoggingHelper.java
metricshub-sql-extension/src/main/java/org/sentrysoftware/metricshub/extension/sql/SqlClientExecutor.java
metricshub-sql-extension/src/main/java/org/sentrysoftware/metricshub/extension/sql/SqlExtension.java
metricshub-sql-extension/src/test/java/org/sentrysoftware/metricshub/extension/sql/SqlClientExecutorTest.java

Add raw data to sourceTable results of SQL Sourcess

Issue #252: Add raw data to sourceTable results of SQL Source

---

metricshub-doc/src/site/markdown/configuration/configure-agent.md
metricshub-linux/src/main/resources/jpackage/metricshub/config/metricshub-example.yaml
metricshub-windows/src/main/resources/jpackage/MetricsHub/config/metricshub-example.yaml

Updated metricshub-example.yaml

Issue #254: Add an SNMP v3 example on metricshub-example.yaml

---

pom.xml

Issue #256: Unsupported charsets EUC-KR, Big5 and Big5-HKSCS error on windows

---

metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/MetricNormalizationService.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/strategy/HardwareStrategy.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/AbstractMetricNormalizer.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/CpuMetricNormalizer.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/FanMetricNormalizer.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/GpuMetricNormalizer.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/LogicalDiskMetricNormalizer.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/LunMetricNormalizer.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/MemoryMetricNormalizer.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/NetworkMetricNormalizer.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/OtherDeviceMetricNormalizer.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/PhysicalDiskMetricNormalizer.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/RoboticsMetricNormalizer.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/TapeDriveMetricNormalizer.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/TemperatureMetricNormalizer.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/VoltageMetricNormalizer.java

- Create the metrics normalization service
- Add the normalization classes for each hardware monitor type
- Call the created normalization service in HardwareStrategy

Issue #238: Hardware Enrichment - Adjust Hardware Thresholds - Skeleton setup

---

metricshub-ipmi-extension/src/main/java/org/sentrysoftware/metricshub/extension/ipmi/IpmiExtension.java
metricshub-ipmi-extension/src/test/java/org/sentrysoftware/IpmiExtensionTest.java

* Refactored IPMI extension to call some method with the configuration hostname.
* Refactored unit tests to include a hostname in IpmiConfigurations.
* Tested all changes using the MetricsHub Agent.

Issue #218: Add a hostname to be used as a class member for IPMI

---

metricshub-http-extension/src/main/java/org/sentrysoftware/metricshub/extension/http/HttpCriterionProcessor.java
metricshub-http-extension/src/main/java/org/sentrysoftware/metricshub/extension/http/HttpExtension.java
metricshub-http-extension/src/main/java/org/sentrysoftware/metricshub/extension/http/HttpSourceProcessor.java
metricshub-http-extension/src/test/java/org/sentrysoftware/metricshub/extension/http/HttpExtensionTest.java

* Refactored HTTP extension to call some method with the configuration hostname.
* Refactored unit tests to include a hostname in HttpConfigurations.
* Tested all changes using the MetricsHub Agent.

Issue #218: Add a hostname to be used as a class member for HTTP

---

metricshub-hardware/src/it/resources/os/SuperConnectorOsIT/expected/expected.json
metricshub-hardware/src/it/resources/snmp/DellOpenManageIT/expected/expected.json
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/MetricNormalizationService.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/sustainability/VmPowerAndEnergyEstimator.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/AbstractMetricNormalizer.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/CpuMetricNormalizer.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/FanMetricNormalizer.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/GpuMetricNormalizer.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/LogicalDiskMetricNormalizer.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/LunMetricNormalizer.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/MemoryMetricNormalizer.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/NetworkMetricNormalizer.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/OtherDeviceMetricNormalizer.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/PhysicalDiskMetricNormalizer.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/RoboticsMetricNormalizer.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/TapeDriveMetricNormalizer.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/TemperatureMetricNormalizer.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/VoltageMetricNormalizer.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/util/HwConstants.java
metricshub-hardware/src/test/java/org/sentrysoftware/metricshub/hardware/strategy/HardwarePostDiscoveryStrategyTest.java
metricshub-hardware/src/test/java/org/sentrysoftware/metricshub/hardware/threshold/AbstractMetricNormalizerTest.java
metricshub-hardware/src/test/java/org/sentrysoftware/metricshub/hardware/threshold/CpuMetricNormalizerTest.java

Adjust CPU thresholds
* Add CpuMetricNormalizer
* Implement CpuMetricNormalizerTest
* Implement AbstractMetricNormalizerTest

Issue #238: Hardware enrichment (Adjust CPU thresholds)

---

metricshub-doc/src/site/markdown/configuration/configure-agent.md
metricshub-doc/src/site/markdown/index.md

* Added ping to the list of supported protocols whenever needed

Issue #281: Listed ping as a supported protocol

---

metricshub-doc/pom.xml

* Added maven source plugin on metricshub-doc pom.xml to generate sources jar.

Issue #298: Produce Source Artifact for `metricshub-doc`

---

metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/MetricNormalizationService.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/OtherDeviceMetricNormalizer.java
metricshub-hardware/src/test/java/org/sentrysoftware/metricshub/hardware/threshold/MemoryMetricNormalizerTest.java
metricshub-hardware/src/test/java/org/sentrysoftware/metricshub/hardware/threshold/OtherDeviceMetricNormalizerTest.java

- Add OtherDeviceMetricNormalizer
- Add unit test
- Update MetricNormalizationService

Issue #238: Hardware Enrichment Adjust Other Device Thresholds

---

metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/MetricNormalizationService.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/LunMetricNormalizer.java
metricshub-hardware/src/test/java/org/sentrysoftware/metricshub/hardware/threshold/LunMetricNormalizerTest.java

* Create LunMetricNormalizer
* Add LunMetricNormalizerTest
* Call LunMetricNormalizer in MetricNormalizationService

Issue #238: Hardware Enrichment - Adjust LUN Thresholds

---

metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/common/helpers/KnownMonitorType.java
metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/common/helpers/KnownMonitorTypeTest.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/MetricNormalizationService.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/NetworkMetricNormalizer.java
metricshub-hardware/src/test/java/org/sentrysoftware/metricshub/hardware/threshold/NetworkMetricNormalizerTest.java

* Create NetworkMetricNormalizer
* Add NetworkMetricNormalizerTest
* Call NetworkMetricNormalizer in MetricNormalizationService

Issue #238: Hardware Enrichment - Adjust NETWORK Thresholds

---

metricshub-hardware/src/it/resources/os/SuperConnectorOsIT/expected/expected.json
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/MetricNormalizationService.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/PhysicalDiskMetricNormalizer.java
metricshub-hardware/src/test/java/org/sentrysoftware/metricshub/hardware/threshold/PhysicalDiskMetricNormalizerTest.java

* Add PhysicalDiskMetricNormalizer
* Create unit tests
* Update ITest expected output file
* Call PhysicalDiskMetricNormalizer in MetricNormalizationService

Issue #238: Hardware Enrichment - Adjust physical disk Thresholds

---

metricshub-hardware/src/it/resources/os/SuperConnectorOsIT/expected/expected.json
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/MetricNormalizationService.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/TapeDriveMetricNormalizer.java
metricshub-hardware/src/test/java/org/sentrysoftware/metricshub/hardware/threshold/TapeDriveMetricNormalizerTest.java

* Add TapeDriveMetricNormalizer
* Create unit tests
* Update ITest expected output file
* Call TapeDriveMetricNormalizer in MetricNormalizationService

Issue #238: Hardware Enrichment - Adjust Tape Drive Thresholds

---

metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/AbstractMetricNormalizer.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/FanMetricNormalizer.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/GpuMetricNormalizer.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/OtherDeviceMetricNormalizer.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/TemperatureMetricNormalizer.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/VoltageMetricNormalizer.java
metricshub-hardware/src/test/java/org/sentrysoftware/metricshub/hardware/threshold/AbstractMetricNormalizerTest.java

* Add replaceLimitType method
* Update FanMetricNormalizer
* Update GpuMetricNormalizer
* Update OtherDeviceMetricNormalizer
* Update TemperatureMetricNormalizer
* Update VoltageMetricNormalizer

Issue #238: Hardware Enrichment  Update Limit_type Replacement  Thresholds

---

metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/service/protocol/SshConfigCli.java
metricshub-agent/src/test/java/org/sentrysoftware/metricshub/cli/service/protocol/SshConfigCliTest.java
metricshub-doc/src/site/markdown/configuration/configure-monitoring.md
metricshub-doc/src/site/markdown/troubleshooting/cli.md
metricshub-linux/src/main/resources/jpackage/metricshub/config/metricshub-example.yaml
metricshub-oscommand-extension/src/main/java/org/sentrysoftware/metricshub/extension/oscommand/OsCommandRequestExecutor.java
metricshub-oscommand-extension/src/main/java/org/sentrysoftware/metricshub/extension/oscommand/OsCommandService.java
metricshub-oscommand-extension/src/main/java/org/sentrysoftware/metricshub/extension/oscommand/SshConfiguration.java
metricshub-oscommand-extension/src/test/java/org/sentrysoftware/metricshub/extension/oscommand/OsCommandExtensionTest.java
metricshub-oscommand-extension/src/test/java/org/sentrysoftware/metricshub/extension/oscommand/OsCommandHelperTest.java
metricshub-windows/src/main/resources/jpackage/MetricsHub/config/metricshub-example.yaml
pom.xml

* Update SshConfiguration, OsCommandService, SshConfigCli, OsCommandRequestExecutor, OsCommandExtensionTest, OsCommandHelperTest, pom.xml and documentation.
* Tested the Ssh protocol

Issue #323: Ability to customize the SSH port number

---

metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/collect/ProtocolHealthCheckStrategy.java

Issue #255: New Metric Implementation: metricshub.host.up.response_time{protocol="<protocol>"}

---

metricshub-doc/src/site/site.xml

* Applied the latest changes required

Issue #288: Review the user doc structure

---

metricshub-snmp-extension-common/src/main/java/org/sentrysoftware/metricshub/extension/snmp/detection/SnmpGetNextCriterionProcessor.java
metricshub-snmp-extension-common/src/test/java/org/sentrysoftware/metricshub/extension/snmp/detection/SnmpGetNextCriterionProcessorTest.java

- Update SnmpGetNextCriterionProcessor.java
- Update Unit test

Issue #267: NullPointerException thrown when calling SNMP Get Next

---

metricshub-doc/src/site/markdown/sustainability/configure-sustainability-metrics.md
metricshub-doc/src/site/site.xml

- Update configure-hardware-extension.md
- Rename configure-hardware-extension.md to configure-sustainability-metrics.md

Issue #338: Update Hardware Extension Document Title for Better Clarity

---

README.md

* Updated maven link in the requirements section.

Issue #353: Updated maven link in the requirements section of `README.md`

---

metricshub-doc/src/site/markdown/install/docker.md

Issue #358: Update Documentation: Docker.md for Enterprise Edition

---

metricshub-doc/pom.xml
metricshub-doc/src/site/markdown/guides/cli.md
metricshub-doc/src/site/markdown/index.md
metricshub-doc/src/site/markdown/install/debian-linux.md
metricshub-doc/src/site/markdown/install/docker.md
metricshub-doc/src/site/markdown/install/redhat-linux.md
metricshub-doc/src/site/markdown/install/windows.md

* Various updates after review.

Issue #399: Documentation review

---

pom.xml

Issue #414: Link to MetricsHub Community Connectors 1.0.06

---

metricshub-linux/src/main/resources/jpackage/metricshub/config/metricshub-example.yaml
metricshub-windows/src/main/resources/jpackage/MetricsHub/config/metricshub-example.yaml

* Update metricshub-example message

Issue #455: Update ESXi configuration example in `metricshub-example.yaml`

---

metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/model/identity/criterion/HttpCriterion.java

Correct HttpCriterion toString method to prevent a NullPointerException when no path or url is provided.

Issue #478: Correct HttpCriterion toString method to prevent a NullPointerException when no path or url is provided.

---

metricshub-doc/src/site/markdown/usecases/remote-linux.md
metricshub-doc/src/site/site.xml

Issue #294: Monitoring Remote Linux

---

metricshub-doc/src/site/markdown/configuration/send-telemetry.md

* Changed the references to the debug exporter

Issue #505: Update references to logging exporter

---

metricshub-doc/pom.xml
pom.xml

* Updated main POM and documentation POM.
This pull request includes version updates for various dependencies in the `pom.xml` files to ensure compatibility and leverage the latest features and fixes.
* Updated `enterpriseVersion` from `1.0.01` to `1.0.02` in `metricshub-doc/pom.xml`.
* Updated `metricshub-connector-maven-plugin` version from `1.0.06` to `1.0.07` in `metricshub-doc/pom.xml`.
* Updated `community-connectors.version` from `1.0.06` to `1.0.07` in `pom.xml`.

Issue #512: Prepare MetricsHub Release

---

metricshub-doc/src/site/markdown/troubleshooting/index.md
metricshub-doc/src/site/markdown/troubleshooting/metricshub-logs.md
metricshub-doc/src/site/markdown/troubleshooting/no-data-observability-platforms.md
metricshub-doc/src/site/markdown/troubleshooting/no-data-resources.md
metricshub-doc/src/site/markdown/troubleshooting/otel-logs.md
metricshub-doc/src/site/site.xml

Created the troubleshooting section as specified.

Issue #529: Create a troubleshooting section

---

metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/deserializer/custom/AbstractCollectionDeserializer.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/deserializer/custom/ConnectionTypeSetDeserializer.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/deserializer/custom/DeviceKindSetDeserializer.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/deserializer/custom/ExtendsDeserializer.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/deserializer/custom/NonBlankInLinkedHashSetDeserializer.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/deserializer/custom/PlatformsDeserializer.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/deserializer/custom/SupersedesDeserializer.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/deserializer/custom/TablesDeserializer.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/model/identity/ConnectorIdentity.java
metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/connector/deserializer/ConnectorDeserializerTest.java
metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/connector/deserializer/DetectionDeserializerTest.java
metricshub-engine/src/test/resources/test-files/connector/connector-with-platform-set.yaml

* Update the field platforms under ConnectorIdentity (From String to Set of String)
* Add PlatformsDeserializer
* Update unit tests

Issue #530: Update connector platforms field

---

metricshub-doc/pom.xml
pom.xml

1. MetricsHub Enterprise Edition v1.1.00
2. MetricsHub Connector Maven Plugin v1.0.08
3. MetricsHub Community Connectors v1.0.08
4. MetricsHub Community Edition v1.0.00

Issue #555: Prepare MetricsHub Release

---

metricshub-doc/src/site/site.xml

Updated maven skin version to v6.4.01

Issue #561

---

metricshub-internaldb-extension/src/main/java/org/sentrysoftware/metricshub/extension/internaldb/ColumnMetadata.java
metricshub-internaldb-extension/src/main/java/org/sentrysoftware/metricshub/extension/internaldb/DatabaseHelper.java
metricshub-internaldb-extension/src/main/java/org/sentrysoftware/metricshub/extension/internaldb/SqlClientExecutor.java
metricshub-internaldb-extension/src/test/java/org/sentrysoftware/metricshub/extension/internaldb/SqlClientExecutorTest.java
pom.xml

Make commits manual instead of automatic in InternalDbQuery  sources.

Issue #563: Make commits manual and optimize insert queries

---

metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/HttpCli.java
metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/WmiCli.java

* Made URL required for HttpCli.
* Resolved NPE when password is null on HttpCli & WmiCli.
* Tested on MetricsHub HttpCli.

Issue #572: httpcli fails with NullPointerException

---

pom.xml

Issue #576: Support IPMI-Over-LAN SHA-256 and MD5 authentication algorithms

---

metricshub-jdbc-extension/src/main/java/org/sentrysoftware/metricshub/extension/jdbc/JdbcExtension.java
metricshub-jdbc-extension/src/test/java/org/sentrysoftware/metricshub/extension/jdbc/JdbcConfigurationTest.java
metricshub-jdbc-extension/src/test/java/org/sentrysoftware/metricshub/extension/jdbc/JdbcExtensionTest.java

* Updated JdbcExtension  and JdbcExtensionTest. 
Tesed : 
Oracle 
Before : 
After: 
MySQL: 
After:

Issue #620: Updated Health Check Query to Support Oracle and Cassandra Databases 

---

metricshub-doc/src/site/markdown/installation/debian-linux.md
metricshub-doc/src/site/markdown/installation/docker.md
metricshub-doc/src/site/markdown/installation/redhat-linux.md
metricshub-doc/src/site/markdown/installation/windows.md

* Added a note at the beginning of each installation page indicating the version supported by MetricsHub

Issue #632: List the supported operating systems

---

metricshub-doc/src/site/markdown/release-notes.md

- Added new features and improvements for MetricsHub Enterprise v1.2.00
- Added new features and improvements for MetricsHub Enterprise Connectors v105
- Added new features and improvements for MetricsHub Community Edition v1.0.02
- Added new features and improvements for MetricsHub Community Connectors v1.0.09

Issue #635: Updated release notes

---

metricshub-doc/pom.xml

- Bumped plugin version from 1.0.10 to 1.0.11

Issue #648: Incorrect connection types reported in the documentation

---

metricshub-doc/src/site/markdown/troubleshooting/no-data-observability-platforms.md

- Corrected anchor in otelcol log reference link
- Updated file extension in the link to `.md`
---- 
Testing

Issue #656: Updated link in troubleshooting doc to fix incorrect anchor

---

metricshub-doc/src/site/markdown/troubleshooting/self-observability.md
metricshub-doc/src/site/site.xml

* Add self-observability.md
Update metric names per https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v2.0.0
Add the Java agent option `-Dotel.exporter.otlp.protocol=grpc` 
* Update site.xml
Added a “Self-Observability” entry under the Troubleshooting menu
https://github.com/user-attachments/assets/8a2b232f-a6c2-4cc8-bdda-88e73944ee84

Issue #655: Document Self-Observability

---

metricshub-agent/pom.xml
metricshub-engine/pom.xml
metricshub-hardware/pom.xml
metricshub-http-extension/pom.xml
metricshub-internaldb-extension/pom.xml
metricshub-ipmi-extension/pom.xml
metricshub-jawk-extension/pom.xml
metricshub-jdbc-extension/pom.xml
metricshub-oscommand-extension/pom.xml
metricshub-ping-extension/pom.xml
metricshub-snmp-extension-common/pom.xml
metricshub-snmp-extension/pom.xml
metricshub-snmpv3-extension/pom.xml
metricshub-wbem-extension/pom.xml
metricshub-win-extension-common/pom.xml
metricshub-winrm-extension/pom.xml
metricshub-wmi-extension/pom.xml

Issue #663: Fix build when path to Maven includes whitespaces

---

metricshub-jawk-extension/src/main/java/org/metricshub/extension/jawk/JawkSourceExtension.java

- Removed premature optimization through `EXTENSIONS_MAP` field and related logic.
- Simplified extension map creation using `Collectors.toConcurrentMap`.
- Replaced `resultBytesStream.toString()` with UTF-8 encoding.
- Improved code readability and maintainability.
- Removed redundant `hostId` variable and associated logic.
Testing (No more NPE)

Issue #674: Multi-threaded NullPointerException in MetricsHub JAWK Extension due to Non-thread-safe Globals

---

pom.xml

- Updated parent version to 3 from 3-SNAPSHOT
- Updated community-connectors.version to 1.0.11

Issue #686: Update Project Dependencies

---

metricshub-engine/src/main/java/org/metricshub/engine/strategy/source/compute/ComputeProcessor.java
metricshub-engine/src/test/java/org/metricshub/engine/strategy/source/compute/ComputeProcessorTest.java

Fix NumberFormatException error during Hex to number conversion
* Refactor convertHex2Dec
* Create unit tests

Issue #703: Fix NumberFormatException error during Hex to number conversion

---

metricshub-doc/src/site/markdown/configuration/configure-monitoring.md
metricshub-doc/src/site/markdown/configuration/send-telemetry.md

* Updated the SchemaStore link in both **configure-monitoring.md** and **send-telemetry.md** files

Issue #708 Fix the SchemaStore Link

---

metricshub-doc/src/site/markdown/custom/database-query.md
metricshub-doc/src/site/markdown/custom/linux-process.md
metricshub-doc/src/site/markdown/custom/linux-service.md
metricshub-doc/src/site/markdown/custom/snmp-polling.md
metricshub-doc/src/site/markdown/custom/web-request.md
metricshub-doc/src/site/markdown/custom/windows-process.md
metricshub-doc/src/site/markdown/custom/windows-service.md
metricshub-doc/src/site/site.xml

This pull request introduces a new guide for configuring database query monitoring using JDBC in MetricsHub and includes several documentation updates for consistency and navigation improvements. Below is a summary of the most important changes:
* Added a comprehensive guide in `custom/database-query.md` for configuring MetricsHub to monitor SQL-compatible databases via JDBC. The guide includes YAML configuration examples, mapping database query results to OpenTelemetry metrics, and instructions for adding unsupported JDBC drivers.
* Updated internal links in multiple files (`linux-process.md`, `linux-service.md`, `windows-process.md`, `windows-service.md`) to use `.md` extensions instead of `.html` for consistency. [[1]](diffhunk://#diff-1bc80fbe7d663e6cf429ac4433cbe6283395d5f37bed6b98994 …

Issue #702: Document execute custom SQL queries

---

pom.xml

* Updated community connectors version to `1.0.12`

Issue #724: Update dependency versions before release

---

metricshub-web/react/src/pages/explorer.jsx

- Removed `Button` components and `Box`.

Issue #822: Remove unused MUI components under explorer
