MetricsHub/metricshub-community

metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/model/identity/Detection.java
metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/connector/deserializer/DetectionDeserializerTest.java
metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/connector/model/identity/DetectionTest.java

Connector Detection ConnectionType must be both LOCAL and REMOTE by default

Issue #12: Detection ConnectionType must be LOCAL and REMOTE by default

---

metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/config/protocols/ProtocolsConfig.java
metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/helper/ConfigHelper.java

* Replaced 'winRm' protocol name by 'winrm' in lowercase in the agent.
* Made all the necessary changes to keep the code working.
* Test the changes using the agent.

Issue #43: Replace 'winRm' protocol name in MetricsHub agent by 'winrm'

---

README.md
metricshub-agent/pom.xml

* Replaced all `Hardware` occurrences by `MetricsHub-hardware`

Issue #58: Change MetricsHub groupId

---

metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/helper/ConfigHelper.java
metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/service/task/MonitoringTask.java
metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/service/PrettyPrinterService.java
metricshub-agent/src/test/java/org/sentrysoftware/metricshub/agent/helper/ConfigHelperTest.java
metricshub-agent/src/test/java/org/sentrysoftware/metricshub/agent/service/task/MonitoringTaskTest.java
metricshub-agent/src/test/java/org/sentrysoftware/metricshub/cli/service/MetricsHubCliServiceTest.java
metricshub-agent/src/test/java/org/sentrysoftware/metricshub/cli/service/PrettyPrinterServiceTest.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/common/helpers/MetricsHubConstants.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/AbstractStrategy.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/detection/DetectionStrategy.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/telemetry/MetricFactory.java
metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/detection/DetectionStrategyTest.java
metricshub-hardware/src/it/resources/os/SuperConnectorOsIT/expected/expected.json
metricshub-hardware/src/it/resources/snmp/DellOpenManageIT/expected/expected.json

* Removed the description attribute from the connector monitor.
* The engine collects `metricshub.connector.status` as state set metric.
* The agent forces a definition for `metricshub.connector.status`.
* Added unit tests.

Issue #82: Enhance the collect of `metricshub.connector.status`

---

metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/telemetry/MonitorFactory.java

* Now the `connector_id` is maintained across job cycles.

Issue #87: Fix discarded `connector_id` when connector implements simple

---

metricshub-doc/pom.xml
pom.xml

* Updated MetricsHub Community Connectors version in the main POM
* Updated MetricsHub Connector Maven Plugin version in the doc. POM

Issue #126: Updated dependency versions

---

metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/deserialization/MonitorJobsDeserializer.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/deserializer/custom/AbstractMapDeserializer.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/deserializer/custom/CaseInsensitiveTreeMapDeserializer.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/deserializer/custom/CustomDeserializer.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/deserializer/custom/SourcesDeserializer.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/model/monitor/task/source/Source.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/parser/ConstantsProcessor.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/parser/NodeProcessorHelper.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/parser/SourceKeyProcessor.java
metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/connector/deserializer/DeserializerTest.java
metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/connector/deserializer/DetectionDeserializerTest.java
metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/connector/deserializer/ExtendsDeserializerTest.java
metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/connector/parser/ReferenceResolverProcessorTest.java
metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/connector/parser/SourceKeyProcessorTest.java
metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/connector/parser/TemplateVariableProcessorTest.java
metricshub-engine/src/test/resources/test-files/processor/Connector/Connector.yaml

* Source keys are now generated at the pre processing phase.
* Added unit tests.
* Fixed failed unit tests.
* Removed keys retrieval method from the AbstractMapDeserializer class.

Issue #131: Fixed incorrect source keys when collect type is undefined

---

metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/source/SourceUpdaterProcessor.java
metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/source/SourceUpdaterProcessorTest.java

Add the ability to include executeForEachEntryOf entry values

Issue #48:  Add the ability to include executeForEachEntryOf entry values

---

metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/common/helpers/MetricsHubConstants.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/source/SourceUpdaterProcessor.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/source/compute/ComputeProcessor.java
metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/source/compute/ComputeProcessorTest.java

Improve the append and prepend computes to replace dynamic entries in string values
Unit tests

Issue #134:  Improve the append and prepend computes to replace dynamic entries in string values

---

metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/model/common/ExecuteForEachEntryOf.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/model/monitor/task/source/Source.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/source/SourceUpdaterProcessor.java
metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/connector/deserializer/source/HttpSourceDeserializerTest.java
metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/source/SourceUpdaterProcessorTest.java

Add the possibility to wait between each request of an executeForEachEntryOf source

Issue #139: Add a sleep input to executeForEachEntryOf

---

metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/config/otel/OtelCollectorConfig.java
metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/process/config/ProcessOutput.java
metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/process/io/ProcessorHelper.java
metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/process/io/Slf4jSafeStreamProcessor.java
metricshub-agent/src/test/java/org/sentrysoftware/metricshub/agent/process/io/ProcessorHelperTest.java
metricshub-agent/src/test/java/org/sentrysoftware/metricshub/agent/process/io/Slf4jSafeStreamProcessorTest.java

* On Windows the executable filename is set to `otelcol-contrib.exe`
* Now OTEL logs are protected using `Slf4jSafeStreamProcessor`

Issue #158: Fixed logging and OTEL Collector executable filename

---

metricshub-engine/pom.xml
metricshub-oscommand-extension/pom.xml
metricshub-oscommand-extension/src/main/java/org/sentrysoftware/metricshub/extension/oscommand/OsCommandService.java
metricshub-oscommand-extension/src/test/java/org/sentrysoftware/metricshub/extension/oscommand/OsCommandExtensionTest.java
metricshub-oscommand-extension/src/test/java/org/sentrysoftware/metricshub/extension/oscommand/OsCommandHelperTest.java

* Removed all remote windows checks and configurations from the OsCommandExtension since they will be handled in Wmi and WinRm extensions.
* Removed all remote windows checks and configurations from the OsCommand Extension tests.
* Remoted Http dependency from the MetricsHub engine.

Issue #165: Remove Windows configurations and checks from OsCommandExtension

---

metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/client/ClientsExecutor.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/common/helpers/NetworkHelper.java
metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/common/helpers/NetworkHelperTest.java

* Developed NetworkHelper#createUrl to detect and protect IPv6 before building the Java URL object.

Issue #161: Fixed IPv6 failures for WBEM queries

---

metricshub-doc/pom.xml
pom.xml

* Updated Community Connectors version to 1.0.01.
* The documentation invokes the MetricsHub Connector Maven Plugin 1.0.01.

Issue #182: Use MetricsHub Community Connectors 1.0.01

---

metricshub-doc/src/site/site.xml

* updated site.xml with the actual URL

Issue 149: GitHub link generates a 404 error page

---

metricshub-engine/pom.xml
metricshub-wbem-extension/pom.xml

* Removed vcenter dependency from engine's POM and moved to metricshub-wbem-extension.

Issue #215: Removed vcenter dependency from the engine

---

metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/AbstractStrategy.java

Add a test to check if the source table is empty before starting the computes.

Issue #242:  NPE thrown by the ComputeProcessor due to a null SourceTable.table

---

metricshub-ipmi-extension/src/main/java/org/sentrysoftware/metricshub/extension/ipmi/IpmiConfiguration.java
metricshub-snmp-extension/src/main/java/org/sentrysoftware/metricshub/extension/snmp/SnmpConfiguration.java
metricshub-snmpv3-extension/src/main/java/org/sentrysoftware/metricshub/extension/snmpv3/SnmpV3Configuration.java
metricshub-wbem-extension/src/main/java/org/sentrysoftware/metricshub/extension/wbem/WbemConfiguration.java
metricshub-winrm-extension/src/main/java/org/sentrysoftware/metricshub/extension/winrm/WinRmConfiguration.java

* Added skip null annotation on Wbem port, protocol and timeout
* Added skip null annotation on WinRm port and timeout
* Replaced all @Builder.Default annotations with @default in the different protocol extension configurations.
* Tested all the changes on MetricsHub agent

Issue #241: missing skip null annotation on port field leads to configuration issues

---

metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/helper/ConfigHelper.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/configuration/HostConfiguration.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/detection/DetectionStrategy.java
metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/constants/Constants.java
metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/detection/AutomaticDetectionTest.java
metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/detection/DetectionStrategyTest.java
metricshub-hardware/src/it/resources/os/SuperConnectorOsIT/expected/expected.json
metricshub-hardware/src/it/resources/snmp/DellOpenManageIT/expected/expected.json
metricshub-oscommand-extension/src/it/resources/os/SuperConnectorOsIT/expected/expected.json
metricshub-snmp-extension/src/it/resources/snmp/DellOpenManageIT/expected/expected.json

- Updated  DetectionStrategy,
DetectionStrategyTest,
ConfigHelper,
HostConfiguration,
Constants,
expected.json in metricshub-oscommand-extension,
expected.json in metricshub-snmp-extension and
expected.json in metricshub-hardware

Issue #228:  Add connector display name as attribute of metricshub.connector.status

---

metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/common/helpers/MetricsHubConstants.java

* Set THREAD_TIMEOUT to 2 minutes

Issue #229: Bad THREAD_TIMEOUT value in MetricsHubConstant

---

.github/workflows/maven-build.yml
metricshub-oscommand-extension/src/main/java/org/sentrysoftware/metricshub/extension/oscommand/OsCommandService.java
metricshub-oscommand-extension/src/test/java/org/sentrysoftware/metricshub/extension/oscommand/OsCommandHelperTest.java

Updated OsCommandService
Updated OsCommandHelperTest

Issue #232: Linux Connector CLI Not Functioning Locally

---

metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/service/protocol/SnmpV3ConfigCli.java
metricshub-agent/src/test/java/org/sentrysoftware/metricshub/cli/service/protocol/SnmpV3ConfigCliTest.java
metricshub-doc/src/site/markdown/configuration/configure-agent.md
metricshub-doc/src/site/markdown/troubleshooting/cli.md
metricshub-linux/src/main/resources/jpackage/metricshub/config/metricshub-example.yaml
metricshub-snmp-extension-common/src/main/java/org/sentrysoftware/metricshub/extension/snmp/ISnmpConfiguration.java
metricshub-snmp-extension/src/main/java/org/sentrysoftware/metricshub/extension/snmp/SnmpRequestExecutor.java
metricshub-snmpv3-extension/pom.xml
metricshub-snmpv3-extension/src/main/java/org/sentrysoftware/metricshub/extension/snmpv3/SnmpV3Configuration.java
metricshub-snmpv3-extension/src/main/java/org/sentrysoftware/metricshub/extension/snmpv3/SnmpV3Extension.java
metricshub-snmpv3-extension/src/main/java/org/sentrysoftware/metricshub/extension/snmpv3/SnmpV3RequestExecutor.java
metricshub-snmpv3-extension/src/test/java/org/sentrysoftware/metricshub/extension/snmpv3/SnmpV3ConfigurationTest.java
metricshub-snmpv3-extension/src/test/java/org/sentrysoftware/metricshub/extension/snmpv3/SnmpV3ExtensionTest.java
metricshub-windows/src/main/resources/jpackage/MetricsHub/config/metricshub-example.yaml

Updated configure-agent.md,
cli.md,
metricshub-example.yaml,
ISnmpConfiguration,
SnmpV3Configuration,
SnmpV3Extension,
SnmpV3RequestExecutor,
SnmpV3ConfigCliTest,
SnmpRequestExecutor,
SnmpV3ConfigurationTest,
and SnmpV3ExtensionTest
Tested the SNMPV3 protocol using the engine and the agent.
Reduced JaCoCo coverage in Metricshub SNMPV3 Project.

Issue #258: Remove Community from SNMP v3 configuration

---

metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/helper/ConfigHelper.java
metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/service/MetricsHubCliService.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/configuration/IConfiguration.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/detection/DetectionStrategy.java
metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/configuration/OsCommandTestConfiguration.java
metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/extension/TestConfiguration.java
metricshub-hardware/src/it/java/org/sentrysoftware/metricshub/hardware/it/DellOpenManageIT.java
metricshub-http-extension/src/main/java/org/sentrysoftware/metricshub/extension/http/HttpConfiguration.java
metricshub-http-extension/src/test/java/org/sentrysoftware/metricshub/extension/http/HttpExtensionTest.java
metricshub-ipmi-extension/src/main/java/org/sentrysoftware/metricshub/extension/ipmi/IpmiConfiguration.java
metricshub-ipmi-extension/src/test/java/org/sentrysoftware/IpmiExtensionTest.java
metricshub-oscommand-extension/src/main/java/org/sentrysoftware/metricshub/extension/oscommand/OsCommandConfiguration.java
metricshub-oscommand-extension/src/test/java/org/sentrysoftware/metricshub/extension/oscommand/OsCommandExtensionTest.java
metricshub-ping-extension/src/main/java/org/sentrysoftware/metricshub/extension/ping/PingConfiguration.java
metricshub-ping-extension/src/main/java/org/sentrysoftware/metricshub/extension/ping/PingExtension.java
metricshub-ping-extension/src/test/java/org/sentrysoftware/metricshub/extension/ping/PingExtensionTest.java
metricshub-snmp-extension/src/main/java/org/sentrysoftware/metricshub/extension/snmp/SnmpConfiguration.java
metricshub-snmp-extension/src/test/java/org/sentrysoftware/metricshub/extension/snmp/SnmpExtensionTest.java
metricshub-snmpv3-extension/src/main/java/org/sentrysoftware/metricshub/extension/snmpv3/SnmpV3Configuration.java
metricshub-snmpv3-extension/src/test/java/org/sentrysoftware/metricshub/extension/snmpv3/SnmpV3ExtensionTest.java
metricshub-wbem-extension/src/main/java/org/sentrysoftware/metricshub/extension/wbem/WbemConfiguration.java
metricshub-wbem-extension/src/test/java/org/sentrysoftware/metricshub/extension/wbem/WbemExtensionTest.java
metricshub-win-extension-common/src/test/java/org/sentrysoftware/metricshub/extension/win/WmiTestConfiguration.java
metricshub-winrm-extension/src/main/java/org/sentrysoftware/metricshub/extension/winrm/WinRmConfiguration.java
metricshub-winrm-extension/src/test/java/org/sentrysoftware/metricshub/extension/winrm/WinRmExtensionTest.java
metricshub-wmi-extension/src/main/java/org/sentrysoftware/metricshub/extension/wmi/WmiConfiguration.java
metricshub-wmi-extension/src/test/java/org/sentrysoftware/metricshub/extension/wmi/WmiExtensionTest.java

* Added getHostname() and setHostname() methods on IConfiguration interface which consequently required adding it on some IConfiguration subclasses.
* Added hostname attribute on all the configurations.
* Refactored ConfigHelper to add the hostname on each configuration if it's null.
* Refactored MetricsHubCliService to add hostname on each configuration.
* Refactored Ping Extension to handle the new Hostname.
* Tested using both the configurations:
```yaml
ping-custom-vmname:
attributes:
host.name: custom-ping-vmname
host.type: windows
protocols:
ping:
hostname: vmname
ping-stock-vmname:
attributes:
host.name: vmname
host.type: windows
protocols:
ping:
```
Both work fine!

Issue #218: Add a `hostname` to be used as a class member for ping

---

metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/MetricNormalizationService.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/strategy/HardwareStrategy.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/AbstractMetricNormalizer.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/CpuMetricNormalizer.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/FanMetricNormalizer.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/GpuMetricNormalizer.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/LogicalDiskMetricNormalizer.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/LunMetricNormalizer.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/MemoryMetricNormalizer.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/NetworkMetricNormalizer.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/OtherDeviceMetricNormalizer.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/PhysicalDiskMetricNormalizer.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/RoboticsMetricNormalizer.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/TapeDriveMetricNormalizer.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/TemperatureMetricNormalizer.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/VoltageMetricNormalizer.java

* Create the metrics normalization service
* Add the normalization classes for each hardware monitor type
* Call the created normalization service in HardwareStrategy

Issue #238: Hardware Enrichment - Adjust Hardware Thresholds - Skeleton setup

---

metricshub-doc/src/site/site.xml

* Renamed `Community Connectors Reference` to `Connectors Reference`.
* Renamed `Community Connector Platforms` to `Connector Platforms`.

Issue #304: Rename Appendix pages in the documentation

---

metricshub-doc/pom.xml
metricshub-doc/src/site/markdown/develop/connector.md
metricshub-doc/src/site/markdown/install.md
metricshub-doc/src/site/markdown/quick-start-community-prometheus-linux.md
metricshub-doc/src/site/markdown/quick-start-community-prometheus-windows.md

* Updated the `pom.xml` file to include the new maven properties.
* Used `${communityVersion}` where the Community version is needed.
* Used `${enterpriseVersion}` where the Enterprise version is needed.
* Used `${otelVersion}` where the OpenTelemetry version is needed.

Issue #318: Separate Maven Properties for Community and Enterprise

---

metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/helper/AgentConstants.java
metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/helper/ConfigHelper.java
metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/security/PasswordEncrypt.java
metricshub-doc/src/site/markdown/quick-start-community-prometheus-windows.md

* Changed the MetricsHub's configuration & logging directory names to `MetricsHub` in PascalCase.
* Updated MetricsHub Documentation to replace `C:\ProgramData\metricshub` by `C:\ProgramData\MetricsHub`.
* Tested the changes.

Issue #321: Update MetricsHub configuration repository name on Windows

---

metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/source/SourceProcessor.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/source/compute/ComputeProcessor.java
metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/source/SourceProcessorTest.java

* SourceTable.lineToList is called now to correctly convert `TableJoin.defaultRightLine` and `Json2Csv.properties` to list of strings.

Issue #333: Fix Improper Default Right Line Interpretation

---

metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/client/ClientsExecutor.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/AbstractAllAtOnceStrategy.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/collect/CollectStrategy.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/detection/CriterionProcessor.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/source/SourceProcessor.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/source/SourceUpdaterProcessor.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/utils/ForceSerializationHelper.java
metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/detection/CriterionProcessorTest.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/util/HwCollectHelper.java
metricshub-oscommand-extension/src/main/java/org/sentrysoftware/metricshub/extension/oscommand/CommandLineSourceProcessor.java

- Update ClientsExecutor, AbstractAllAtOnceStrategy, CollectStrategy, CriterionProcessor, SourceProcessor, SourceUpdaterProcessor, ForceSerializationHelper, HwCollectHelper, CommandLineSourceProcessor and CriterionProcessorTest

Issue #272: Replace all telemetryManager.getHostConfiguration().getHostname() occurrences 

---

metricshub-doc/pom.xml
metricshub-doc/src/site/resources/css/site.css
metricshub-doc/src/site/site.xml

* Upgraded MetricsHub Connector Maven Plugin to `1.5.00`.

Issue #350: Use MetricsHub Connector Maven Plugin `1.5.00`

---

metricshub-hardware/src/it/resources/os/SuperConnectorOsIT/connectors/SuperConnectorOS/SuperConnectorOS.yaml
metricshub-hardware/src/it/resources/snmp/DellOpenManageIT/connectors/DellOpenManage/DellOpenManage.yaml
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/HardwareEnergyPostExecutionService.java
metricshub-hardware/src/test/java/org/sentrysoftware/metricshub/hardware/HardwareEnergyPostExecutionServiceTest.java
metricshub-hardware/src/test/java/org/sentrysoftware/metricshub/hardware/strategy/HardwareStrategyTest.java
metricshub-hardware/src/test/resources/Linux/Linux.yaml
metricshub-hardware/src/test/resources/Linux/memory.awk
metricshub-hardware/src/test/resources/Linux/network.awk
metricshub-hardware/src/test/resources/strategy/collect/TestConnector.yaml

Exclude non hardware monitors from power estimation
* Add connectorHasHardwareTag to compute power only for hardware monitors
* Update unit tests

Issue #352: Exclude non hardware items from power estimation

---

metricshub-http-extension/src/main/java/org/sentrysoftware/metricshub/extension/http/utils/HttpMacrosUpdater.java
metricshub-http-extension/src/test/java/org/sentrysoftware/metricshub/extension/http/utils/HttpMacrosUpdaterTest.java

* Escaped chars (\ " \n \r \t) for `%{PASSWORD_JSON}` and `%{USERNAME_JSON}` values.

Issue #355: Added support for `%{PASSWORD_JSON}` and `%{USERNAME_JSON}`

---

metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/AbstractStrategy.java

* Added a check to log a warning and set the source table to an empty instance if it is null or empty.
* Ensured that the source table is always added to the connector namespace, preventing failures in downstream operations like table joins and computes.

Issue #363: Handle null or empty source table by setting it to an empty

---

metricshub-snmp-extension/src/main/java/org/sentrysoftware/metricshub/extension/snmp/SnmpConfiguration.java
metricshub-snmp-extension/src/test/java/org/sentrysoftware/metricshub/extension/snmp/SnmpConfigurationTest.java

* Updated SnmpConfiguration to accept '2c' as a valid SNMP version.

Issue #366: Recognize '2c' as a valid SNMP version option

---

metricshub-wmi-extension/pom.xml
metricshub-wmi-extension/src/main/java/org/sentrysoftware/metricshub/extension/wmi/WmiRequestExecutor.java

* Ignored WMI Password when WMI Username isn't provided
* Added test cases.
* Tested the results using the CLI and the Agent.

Issue #297: Manage WMI Empty Username

---

metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/config/AgentConfig.java
metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/config/ResourceConfig.java
metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/config/ResourceGroupConfig.java
metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/config/StateSetMetricCompression.java
metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/helper/ConfigHelper.java
metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/service/signal/AbstractNotCompressedStateMetricObserver.java
metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/service/signal/AbstractStateMetricObserver.java
metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/service/signal/AbstractSuppressZerosStateMetricObserver.java
metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/service/signal/CounterStateMetricObserver.java
metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/service/signal/CounterSuppressZerosStateMetricObserver.java
metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/service/signal/GaugeSuppressZerosStateMetricObserver.java
metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/service/signal/MetricTypeVisitor.java
metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/service/signal/UpDownCounterStateMetricObserver.java
metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/service/signal/UpDownCounterSuppressZerosStateMetricObserver.java
metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/service/task/MonitoringTask.java
metricshub-agent/src/test/java/org/sentrysoftware/metricshub/agent/service/signal/CounterSuppressZerosStateMetricObserverTest.java
metricshub-agent/src/test/java/org/sentrysoftware/metricshub/agent/service/signal/GaugeSuppressZerosStateMetricObserverTest.java
metricshub-agent/src/test/java/org/sentrysoftware/metricshub/agent/service/signal/UpDownCounterSuppressZerosStateMetricObserverTest.java
metricshub-agent/src/test/java/org/sentrysoftware/metricshub/agent/service/task/MonitoringTaskTest.java
metricshub-doc/src/site/markdown/configuration/configure-monitoring.md

* Developed new classes to handle `suppressZeros` compression for StateSet metrics.
* Initialized the `suppressZeros` compression observers.
* Updated the configuration model to enable user configuration for compression.
* Added a new section to the documentation (Monitoring Configuration).

Issue #380: Implement StateSet metrics compression

---

metricshub-doc/src/site/markdown/index.md
metricshub-doc/src/site/site.xml

* Updated site.xml to move the Connectors Directory item.
* Updated incorrect link in `index.md`.

Issue #385: Move Connectors Directory to Introduction

---

metricshub-doc/src/site/markdown/troubleshooting/status.md

* Replaced Hardware Sentry Agent with MetricsHub Agent

Issue 394: Removed reference to Hardware Sentry Agent

---

metricshub-doc/src/site/markdown/configuration/send-telemetry.md
metricshub-doc/src/site/site.xml

* Renamed the topic Sending Telemetry Data to Observability Platforms
* Renamed the send-data.md file to send-telemetry.md
* Updated site.xml
* Replaced "Configure the OTLP Receiver" with "Configure the OTLP Exporter"

Issue 393: Data export topic is misleading

---

metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/utils/MappingProcessor.java
metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/utils/MappingProcessorTest.java
metricshub-hardware/src/it/resources/os/SuperConnectorOsIT/expected/expected.json
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/HardwareEnergyPostExecutionService.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/sustainability/NetworkPowerAndEnergyEstimator.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/util/HwCollectHelper.java
metricshub-hardware/src/test/java/org/sentrysoftware/metricshub/hardware/sustainability/NetworkPowerAndEnergyEstimatorTest.java
metricshub-oscommand-extension/src/it/resources/os/SuperConnectorOsIT/expected/expected.json

- Implemented the `megaBit2Byte` conversion in the Mapping processor.
- Reported `hw.network.io{direction="transmit|receive"}` in bytes per second instead of bytes per millisecond.
- Corrected the computation of `hw.network.bandwidth.utilization` to ensure that both the dividend and divisor are in the same unit (bytes).
- Adjusted the power estimator for network devices because `hw.network.bandwidth.limit` is now measured in bytes.

Issue #401: Report hw.network.bandwidth.limit in byte/s

---

metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/utils/MappingProcessor.java
metricshub-hardware/src/it/resources/os/SuperConnectorOsIT/expected/expected.json
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/sustainability/VmPowerAndEnergyEstimator.java
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/util/HwConstants.java
metricshub-oscommand-extension/src/it/resources/os/SuperConnectorOsIT/expected/expected.json

* Updated MappingProcessor, MappingProcessorTest, expected.json, VmPowerAndEnergyEstimator and HwConstants.java.
* Tested on Nassim's PC.

Issue  #368:  KM module: issues with the VM class

---

metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/helper/ConfigHelper.java
metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/helper/ConnectorTemplateLibraryParser.java
metricshub-agent/src/test/java/org/sentrysoftware/metricshub/agent/helper/ConnectorTemplateLibraryParserTest.java
metricshub-agent/src/test/resources/connectorTemplateLibraryParser/templateVariable.yaml
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/model/identity/ConnectorDefaultVariable.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/model/identity/ConnectorIdentity.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/parser/ConnectorLibraryParser.java
metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/connector/parser/TemplateVariableProcessorTest.java
metricshub-engine/src/test/resources/test-files/connector/templateVariable/templateVariable.json
metricshub-jawk-extension/src/main/java/org/sentrysoftware/metricshub/extension/jawk/MetricsHubExtensionForJawk.java

* Added support for default connector variables.
* Added unit tests for both the engine and the agent.
* Functionally tested on the MetricsHub agent.
* Minor adjustments on the connector variable parser when encountering
exceptions.

Issue #374: Add the possibility to add default connector variables 

---

metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/model/identity/ConnectorDefaultVariable.java

* ConnectorDefaultVariable implements Serializable
This pull request includes changes to the `ConnectorDefaultVariable` class in the `metricshub-engine` to add serialization support.
Serialization support and Lombok annotations:
* [`metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/model/identity/ConnectorDefaultVariable.java`](diffhunk://#diff-480b199819a934d0cf2c58fd78c2a898f19cdf5cc08d43efe4686133ae66cf68R24-R39): Added `Serializable` interface to the `ConnectorDefaultVariable` class and moved imports to the right location.

Issue #439: Connector default variables are not serializable

---

metricshub-doc/src/site/markdown/configuration/send-telemetry.md
metricshub-doc/src/site/markdown/guides/status.md

**Updates**
* Updated send-telemetry.md as well as status.md.
**Summary**
This pull request involves updates to the `send-telemetry.md` and `status.md` documentation files in the `metricshub-doc` directory. The main change is the removal of the `resourcedetection` processor from the default configuration.
* `metricshub-doc/src/site/markdown/configuration/send-telemetry.md`: Removed the `resourcedetection` processor from the list of default processors and updated the example configuration to reflect this change.
* `metricshub-doc/src/site/markdown/guides/status.md`: Updated the example configuration to remove the `resourcedetection` processor.
**Tests**

Issue #441: Removed resourcedetection from the documentation

---

metricshub-doc/src/site/markdown/installation/debian-linux.md
metricshub-doc/src/site/markdown/installation/docker.md
metricshub-doc/src/site/markdown/installation/redhat-linux.md
metricshub-doc/src/site/markdown/installation/windows.md

**Updates**
* Updated debian-linux.md
* Updated redhat-linux.md
* Updated windows.md
* Updated docker.md
**Summary**
This pull request updates the documentation for installing and upgrading MetricsHub Enterprise across various platforms. The most important changes include adding upgrade instructions for Debian Linux, Docker, RedHat Linux, and Windows.
Upgrade instructions added:
* `metricshub-doc/src/site/markdown/installation/debian-linux.md`: Added detailed steps to upgrade MetricsHub Enterprise on Debian Linux, including stopping the service and using `dpkg` to install the new version.
* `metricshub-doc/src/site/markdown/installation/docker.md`: Provided comprehensive steps to upgrade MetricsHub Enterprise in a Docker environment, including stopping and removing the container, backing …

Issue #448: Document MetricsHub Enterprise upgrade procedure

---

metricshub-wbem-extension/pom.xml
metricshub-wbem-extension/src/main/java/org/sentrysoftware/metricshub/extension/wbem/WbemRequestExecutor.java

**Updates**
* Corrected exception message.
* Updated shade plugin to include the missing dom4j dependency.
**Summary**
This pull request includes changes to the `metricshub-wbem-extension` project, focusing on dependency updates and improved error logging. The most important changes include adding a new dependency in the `pom.xml` file and enhancing the logging details in the `refreshVCenterTicket` method.
Dependency updates:
* [`metricshub-wbem-extension/pom.xml`](diffhunk://#diff-75aa1f5fd111652d256f97eb7d5d9591a24d639e24bd343738ed12c6797c3b86R182): Added `dom4j:dom4j` to the list of included dependencies.
Error logging improvements:
* [`metricshub-wbem-extension/src/main/java/org/sentrysoftware/metricshub/extension/wbem/WbemRequestExecutor.java`](diffhunk://#diff-6cd43ad979f6094e9bf86ce …

Issue #456: Fix missing dom4j dependency in the WBEM extension

---

metricshub-doc/pom.xml
pom.xml

* Upgraded `metricshub-community-connectors` to 1.0.06
* Upgraded  `metricshub-connector-maven-plugin` to 1.0.06
* The `enterpriseVersion` property is set to 1.0.01
This pull request includes version updates in the `pom.xml` files to ensure compatibility and stability across different components.
Version updates:
* [`metricshub-doc/pom.xml`](diffhunk://#diff-77ee4fa86779ba8e7a1d78405285cd8eafedbfc46b476339cb8c7d2d6a40b23aL19-R19): Updated `enterpriseVersion` from `1.0.00` to `1.0.01`.
* [`metricshub-doc/pom.xml`](diffhunk://#diff-77ee4fa86779ba8e7a1d78405285cd8eafedbfc46b476339cb8c7d2d6a40b23aL122-R122): Updated `metricshub-connector-maven-plugin` version from `1.0.05` to `1.0.06`.
* [`pom.xml`](diffhunk://#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8L95-R95): …

Issue #414: Link to MetricsHub Community Connectors 1.0.06

---

metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/AbstractStrategy.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/detection/CriterionProcessor.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/detection/CriterionTestResult.java
metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/collect/CollectStrategyTest.java
metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/detection/CriterionProcessorTest.java
metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/discovery/DiscoveryStrategyTest.java
metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/simple/SimpleStrategyTest.java

* Added a displayCriterionMessage method that displays the same message format for all the CriterionTestResult.
* Adapted unit tests.
* Tested on MetricsHub.

Issue #432: Standardize the messages for all the criteria tests

---

metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/deserialization/PostConfigDeserializer.java

**Update**
* Extended the feature to `AgentConfig` resources.
**Details**
This pull request to `metricshub-agent` introduces changes to the `PostConfigDeserializer` class to manage ResourceConfig instances more effectively by resolving multiple host configurations. The most important changes include adding a new method to handle ResourceConfig instances and updating the deserialization logic to incorporate this method.
Enhancements to deserialization logic:
* [`metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/deserialization/PostConfigDeserializer.java`](diffhunk://#diff-347083d86da737255b9cc7affc2b4b0634e380c57ef753a1517367e968ab3cedR38): Imported `AgentConfig` to manage ResourceConfig instances under the AgentConfig.
* …

Issue #468: Support shared-characteristics for centralized resources

---

metricshub-http-extension/src/main/java/org/sentrysoftware/metricshub/extension/http/HttpExtension.java
metricshub-ipmi-extension/src/main/java/org/sentrysoftware/metricshub/extension/ipmi/IpmiExtension.java
metricshub-oscommand-extension/src/main/java/org/sentrysoftware/metricshub/extension/oscommand/OsCommandExtension.java
metricshub-ping-extension/src/main/java/org/sentrysoftware/metricshub/extension/ping/PingExtension.java
metricshub-snmp-extension/src/main/java/org/sentrysoftware/metricshub/extension/snmp/SnmpExtension.java
metricshub-snmpv3-extension/src/main/java/org/sentrysoftware/metricshub/extension/snmpv3/SnmpV3Extension.java
metricshub-wbem-extension/src/main/java/org/sentrysoftware/metricshub/extension/wbem/WbemExtension.java
metricshub-winrm-extension/src/main/java/org/sentrysoftware/metricshub/extension/winrm/WinRmExtension.java
metricshub-wmi-extension/src/main/java/org/sentrysoftware/metricshub/extension/wmi/WmiExtension.java

* Removed configuration details from logs across all extensions when an exception occurs.
* Tested on MetricsHub.

Issue #472: Prevent sensitive configuration details from being displayed in error logs

---

metricshub-localsql-source-extension/src/main/java/org/sentrysoftware/metricshub/extension/sql/SqlClientExecutor.java
metricshub-localsql-source-extension/src/test/java/org/sentrysoftware/metricshub/extension/sql/SqlClientExecutorTest.java

Process empty values the same way as null values when creating INSERT queries for localSql Sources.

Issue #474: Handle blank values when creating INSERT queries for localSql Sources.

---

metricshub-localsql-source-extension/src/main/java/org/sentrysoftware/metricshub/extension/sql/SqlClientExecutor.java

Process empty values the same way as null values when creating INSERT queries for localSql Sources instead of blank values.

Issue #476 Process empty values the same way as null values when creating INSERT queries for localSql Sources instead of blank values.

---

metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/deserialization/AttributesDeserializer.java
metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/deserialization/PostConfigDeserializer.java
metricshub-agent/src/test/java/org/sentrysoftware/metricshub/agent/context/AgentContextTest.java
metricshub-agent/src/test/java/org/sentrysoftware/metricshub/agent/deserialization/AttributesDeserializerTest.java
metricshub-agent/src/test/java/org/sentrysoftware/metricshub/agent/deserialization/PostConfigDeserializerTest.java
metricshub-agent/src/test/resources/config/metricshub-multi-hosts.yaml
metricshub-agent/src/test/resources/config/metricshub.yaml
metricshub-doc/src/site/markdown/configuration/configure-monitoring.md
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/common/helpers/MetricsHubConstants.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/common/helpers/StringHelper.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/deserialization/MultiValueDeserializer.java
metricshub-http-extension/src/main/java/org/sentrysoftware/metricshub/extension/http/HttpConfiguration.java
metricshub-ipmi-extension/src/main/java/org/sentrysoftware/metricshub/extension/ipmi/IpmiConfiguration.java
metricshub-linux/src/main/resources/jpackage/metricshub/config/metricshub-example.yaml
metricshub-oscommand-extension/src/main/java/org/sentrysoftware/metricshub/extension/oscommand/OsCommandConfiguration.java
metricshub-oscommand-extension/src/main/java/org/sentrysoftware/metricshub/extension/oscommand/SshConfiguration.java
metricshub-oscommand-extension/src/test/java/org/sentrysoftware/metricshub/extension/oscommand/OsCommandExtensionTest.java
metricshub-ping-extension/src/main/java/org/sentrysoftware/metricshub/extension/ping/PingConfiguration.java
metricshub-snmp-extension/src/main/java/org/sentrysoftware/metricshub/extension/snmp/SnmpConfiguration.java
metricshub-snmpv3-extension/src/main/java/org/sentrysoftware/metricshub/extension/snmpv3/SnmpV3Configuration.java
metricshub-wbem-extension/src/main/java/org/sentrysoftware/metricshub/extension/wbem/WbemConfiguration.java
metricshub-windows/src/main/resources/jpackage/MetricsHub/config/metricshub-example.yaml
metricshub-winrm-extension/src/main/java/org/sentrysoftware/metricshub/extension/winrm/WinRmConfiguration.java
metricshub-wmi-extension/src/main/java/org/sentrysoftware/metricshub/extension/wmi/WmiConfiguration.java

This pull request includes several changes to the deserialization logic in the `metricshub-agent` project, focusing on handling multi-value attributes and updating resource configurations. The most important changes include modifications to the `AttributesDeserializer` and `PostConfigDeserializer` classes, as well as updates to the associated tests.
* [`AttributesDeserializer.java`](diffhunk://#diff-e7331969375ae5dccd91666b58e72e951809dd8c1377c464f32f5b6abff31b45R24-R25): Added the `MULTI_VALUE_SEPARATOR` constant to handle multi-value attributes during deserialization. Updated the `deserialize` method to use this separator. [[1]](diffhunk://#diff-e7331969375ae5dccd91666b58e72e951809dd8c1377c464f32f5b6abff31b45R24-R25) [[2]](diffhunk://#diff-e7331969375ae5dccd91666b58e72e951809dd8c1377c464 …

Issue #470: Add support for `host.id`, `host.name`, and other attributes as arrays in resource configuration

---

metricshub-jawk-extension/src/main/java/org/sentrysoftware/metricshub/extension/jawk/MetricsHubExtensionForJawk.java

Use data from the TableSource when RawData is empty in Jawk Sources

Issue #498: Use data from the TableSource when RawData is empty in Jawk Sources

---

metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/collect/CollectStrategy.java

* Resolved an issue in the `CollectStrategy` where mono-instance collect was limited to processing only one connector due to incorrect indexation logic.
* Updated the logic to iterate over all relevant monitors, ensuring that metrics are collected for each connector during mono-instance collect.
This pull request includes a change to the `processMonitorJob` method in the `CollectStrategy` class to simplify the processing of monitors by removing unnecessary intermediate collections and directly iterating over the filtered stream.
Fix monitor processing:
* [`metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/collect/CollectStrategy.java`](diffhunk://#diff-df056a21da0447fb587fcc752797b20168ca4e31e3bb80af1b591c07c5061fdbL269-L287): Removed the creation of the …

Issue #500: Mono-Instance collect processes only one monitor

---

metricshub-doc/src/site/markdown/usecases/network-interfaces.md
metricshub-doc/src/site/markdown/usecases/ping.md
metricshub-doc/src/site/markdown/usecases/process-windows.md
metricshub-doc/src/site/markdown/usecases/remote-linux.md
metricshub-doc/src/site/markdown/usecases/service-health.md
metricshub-doc/src/site/markdown/usecases/service-linux.md

* Fixed YAML examples.
This pull request includes several documentation updates to the `metricshub-doc` repository. The most important changes involve adding the `resources` key to YAML configuration examples and updating timeout values to include units.
YAML configuration updates:
* [`metricshub-doc/src/site/markdown/usecases/network-interfaces.md`](diffhunk://#diff-178092bf70f6ba7891bda965a9699c0665dca90cdd1fdda15c0ae96f694694f5R26): Added the `resources` key to the YAML configuration examples to monitor the switch. [[1]](diffhunk://#diff-178092bf70f6ba7891bda965a9699c0665dca90cdd1fdda15c0ae96f694694f5R26) [[2]](diffhunk://#diff-178092bf70f6ba7891bda965a9699c0665dca90cdd1fdda15c0ae96f694694f5R44)
* [`metricshub-doc/src/site/markdown/usecases/remote-linux.md`](diffhunk://#diff-8891638b6fd …

Issue #515: Fix indentation in monitoring use cases

---

metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/common/helpers/state/LinkStatus.java
metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/common/helpers/state/LinkStatusTest.java

Fixed LinkStatus state mapping.
**Details**
This pull request includes changes to the `LinkStatus` enum and the addition of a new test class to ensure the correct interpretation of state values. The most important changes include updating the `LinkStatus` enum to handle new states and adding a comprehensive test to verify the interpretation logic.
Updates to `LinkStatus` enum:
* [`metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/common/helpers/state/LinkStatus.java`](diffhunk://#diff-41baa07ba58e537649d2b8366fef16e6d546df36a10cf1e7d463231c6262b4eeR74-R85): Added new states "warn" and "alarm" to the `LinkStatus` enum and updated the interpretation logic to classify these states as `UNPLUGGED`.
Addition of test class:
* …

Issue #523: hw.network.up metric not reported for WARN or ALARM states

---

metricshub-doc/src/site/markdown/configuration/configure-monitoring.md
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/connector/model/Connector.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/AbstractAllAtOnceStrategy.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/AbstractStrategy.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/collect/CollectStrategy.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/surrounding/SurroundingStrategy.java
metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/AbstractStrategyTest.java
metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/collect/CollectStrategyTest.java
metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/discovery/DiscoveryStrategyTest.java
metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/simple/SimpleStrategyTest.java
metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/surrounding/AfterAllStrategyTest.java
metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/surrounding/BeforeAllStrategyTest.java

* Compute job duration in validateConnectorDetectionCriteria
* Remove monitorType('none') from surrounding strategy job duration metric
* Add documentation for enableSelfMonitoring in configure-monitoring.md
* Add unit tests

Issue #525: Add job duration metrics to connectors

---

metricshub-doc/src/site/markdown/release-notes.md

This pull request includes updates to the release notes in the `metricshub-doc/src/site/markdown/release-notes.md` file. The changes introduce new sections for MetricsHub Enterprise Connectors v104 and MetricsHub Community Edition v1.0.01, detailing changes and improvements.
Updates to release notes:
* Added a section for MetricsHub Enterprise Connectors v104, including a change to reduce high CPU usage caused by internal DB queries in `NetAppRESTv2` and `PureStorageREST` connectors.
* Added a section for MetricsHub Community Edition v1.0.01, detailing an improvement in memory usage and data types identification for the MetricsHub Engine Internal DB.
---------

Issue #565: Prepare MetricsHub Release 1.0.01

---

metricshub-internaldb-extension/pom.xml
metricshub-internaldb-extension/src/main/java/org/sentrysoftware/metricshub/extension/internaldb/DatabaseHelper.java
metricshub-internaldb-extension/src/test/java/org/sentrysoftware/metricshub/extension/internaldb/DatabaseHelperTest.java

This pull request includes several changes to the `metricshub-internaldb-extension` project, focusing on dependency updates, code enhancements, and the addition of unit tests. The key changes are summarized below:
* Removed the `snmp4j-agent` dependency from the `pom.xml` file.
* Increased the minimum complexity coverage ratio from 0.5 to 0.66 in the `pom.xml` file.
* Modified the `set` method in `DatabaseHelper.java` to trim values for non-String types before parsing to avoid errors.
* Added a private `trimValue` method in `DatabaseHelper.java` to handle the trimming logic.
* Added comprehensive unit tests for the `DatabaseHelper` class in `DatabaseHelperTest.java` to verify the correct behavior of the `set` method for various data types and edge cases.
----

Issue #567: Added unit tests to metricshub-internaldb-extension

---

metricshub-oscommand-extension/src/main/java/org/sentrysoftware/metricshub/extension/oscommand/ipmi/IpmiHelper.java

* Corrected the split responsible of the ArrayIndexOutOfBoundsException where the empty fields weren't retained, which resulted in that exception.
* Reproduced, tested and ensured that the fix resolved the bug.

Issue #577: IPMI Command processing fail with ArrayIndexOutOfBoundsException

---

metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/SnmpV3Cli.java

* Replaced `--retryIntervals` option by `--retry` (or possibly --retry-intervals) as stated for SnmpCLI.
* Tested the fix on MetricsHub.

Issue #580: Incorrect snmpv3cli flag (--retryIntervals instead of --retry)

---

metricshub-agent/src/main/dist/config/metricshub-alertmanager-rules-example.yaml
metricshub-hardware/src/main/java/org/sentrysoftware/metricshub/hardware/threshold/VoltageMetricNormalizer.java
metricshub-hardware/src/test/java/org/sentrysoftware/metricshub/hardware/threshold/VoltageMetricNormalizerTest.java

This pull request includes changes to the `VoltageMetricNormalizer` class and its corresponding test class to update the handling of voltage metrics. The main focus is on replacing the creation of high/low critical metrics with high/low degraded metrics.
Changes to `VoltageMetricNormalizer`:
* Modified the logic to create high degraded metrics instead of high critical metrics when only high critical metrics are present.
* Modified the logic to create low degraded metrics instead of low critical metrics when only low critical metrics are present.
Changes to `VoltageMetricNormalizerTest`:
* Added constants for high degraded and low degraded metric types.
* Updated test cases to verify the creation of high degraded metrics instead of low critical metrics. …

Issue #590: `hw_voltage_limit_volts` is incorrectly collected

---

metricshub-agent/src/main/resources/metricshub-host-metrics.yaml
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/collect/ProtocolHealthCheckStrategy.java
metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/collect/ProtocolHealthCheckStrategyTest.java

This pull request includes several changes to the `ProtocolHealthCheckStrategy` class and related test cases, as well as a modification to the metric names in the `metricshub-host-metrics.yaml` file. The most important changes include renaming metrics, updating the `ProtocolHealthCheckStrategy` class, and enhancing test coverage.
* `metricshub.host.up.response_time` was renamed to `metricshub.host.response_time` in the `metricshub-host-metrics.yaml` file.
* Changed the visibility of constants `UP` and `DOWN` from `public` to package-private and introduced new constants `UP_METRIC_FORMAT` and `RESPONSE_TIME_METRIC_FORMAT` for metric formatting in `ProtocolHealthCheckStrategy.java`.
* Refactored the `run` method to use the new metric format constants for collecting metrics.
* Added new …

Issue #597: Rename host response time to `metricshub.host.response_time`

---

metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/HttpCli.java
metricshub-agent/src/test/java/org/sentrysoftware/metricshub/cli/HttpCliTest.java
metricshub-doc/src/site/markdown/troubleshooting/cli/http.md

* Simplified httpcli options by adding two parameters `positionalMethod` and `positionalUrl` which allow to create CLI requests without using `--method` and `--url`.
* Handled all the possible cases when the user specifies both positional parameters and options.
* Tested on MetricsHub.

Issue #582: Simplify the options required in httpcli

---

metricshub-linux/pom.xml
metricshub-windows/pom.xml

* Removed versions on metricshub extensions to avoid problems when unzipping a new metricshub version on the same metricshub directory where an old version is.
* Tested on MetricsHub windows and linux.

Issue #574: When upgrading from previous version

---

metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/SnmpCli.java
metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/SnmpV3Cli.java
metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/service/protocol/SnmpConfigCli.java
metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/service/protocol/SnmpV3ConfigCli.java
metricshub-doc/src/site/markdown/appendix/cli.md

* Updated CLI Option Definitions.
* Updated Documentation Examples.
* Tested all the Changes
NB: With a short retry intervals time (5,10 milliseconds), the request does not have the time to get executed, which caused the detection to stop.

Issue #608: Fix SNMP CLI retry-intervals option names and update SNMPv3 retry intervals example in documentation

---

metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/collect/ProtocolHealthCheckStrategy.java

* Added a condition to collect `metricshub_response_time_seconds` only if the `metricshub_host_up` is collected as TRUE/1.0.
* Tested successfully on MetricsHub.

Issue #614: metricshub.host.response_time is reported when metricshubhost.up is down

---

metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/AbstractStrategy.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/source/SourceProcessor.java

* Used generateTextTable(List<List<String>> rows) instead of generateTextTable(String[] columns, List<List<String>> rows) to avoid columns display, which corrects the bug.
* Tested the resulted version on MetricsHub.

Issue #619: Incorrect text table display in SNMP logs when adding columns using computes

---

metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/service/PrettyPrinterService.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/AbstractAllAtOnceStrategy.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/telemetry/Monitor.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/telemetry/MonitorFactory.java
metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/discovery/DiscoveryStrategyTest.java
metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/telemetry/MonitorTest.java

This pull request introduces several changes to the `metricshub-agent` and `metricshub-engine` projects to enhance the handling of identifying attributes for monitors. The most significant changes include the addition of methods to format and validate identifying attributes, updates to the `Monitor` and `MonitorFactory` classes, and new test cases to ensure the correctness of these changes.
Enhancements to identifying attributes:
* [`metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/service/PrettyPrinterService.java`](diffhunk://#diff-6b07bf98078c57605f45aeb09f5ecb4b709b16f7433c8c92d921880fa9b3fdf9L365-R364): Modified the `getMonitorDisplayName` and `build` methods to use `formatIdentifyingAttributes` instead of `MONITOR_ATTRIBUTE_ID`. …

Issue #626: Remove mandatory attribute id requirement

---

metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/service/MetricsHubCliService.java
metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/service/protocol/JdbcConfigCli.java
metricshub-doc/src/site/markdown/appendix/cli.md
metricshub-doc/src/site/markdown/configuration/configure-monitoring.md
metricshub-jdbc-extension/src/main/java/org/sentrysoftware/metricshub/extension/jdbc/JdbcConfiguration.java
metricshub-jdbc-extension/src/test/java/org/sentrysoftware/metricshub/extension/jdbc/JdbcConfigurationTest.java

* Rename sqlserver to mssql in generateUrl
* Update unit tests

Issue #623: JDBC URL is not generated when the database type is set to `mssql` in the resource protocol configuration

---

metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/AbstractAllAtOnceStrategy.java
metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/collect/CollectStrategy.java

- Add `isSequential` and `mode` variables for execution mode
- Log execution mode before running monitor jobs
- Remove redundant logging in parallel execution block
- Use `isSequential` variable in conditional checks
- Ensure consistent logging format across strategies
- Maintain existing functionality for sequential and parallel execution
Parallel
Sequential

Issue #643: Added logging for monitor job execution mode (parallel vs sequential)

---

pom.xml

- Bump `wmi-java` version from 1.0.03 to 1.0.05
---
Tests
**before fix**
**after fix**
Thanks for the library fix @bertysentry!

Issue #662: WMI unsigned 32-bit integers incorrectly converted

---

metricshub-hardware/src/main/java/org/metricshub/hardware/util/MonitorNameBuilder.java
metricshub-hardware/src/test/java/org/metricshub/hardware/util/MonitorNameBuilderTest.java

* Fixed NPE in both `humanReadableByteCountSI` and `buildCpuName`.
* Fixed several `Hz` and `byte` conversions.
* Updated unit tests to make them work.
* Tested the updates on MetricsHub.

Issue #680: Fix NPE in MonitorNameBuilder when metric is null

---

metricshub-agent/src/main/java/org/metricshub/agent/service/task/MonitoringTask.java
metricshub-agent/src/test/java/org/metricshub/agent/service/task/MonitoringTaskTest.java
metricshub-hardware/src/main/java/org/metricshub/hardware/strategy/HardwareMonitorNameGenerationStrategy.java
metricshub-hardware/src/main/java/org/metricshub/hardware/strategy/HardwarePostDiscoveryStrategy.java
metricshub-hardware/src/test/java/org/metricshub/hardware/strategy/HardwareMonitorNameGenerationStrategyTest.java

* Add hardware tag and connectorStatusOk filtering to monitors while setting their names

Issue #693: Fix monitor names that are generated for non-Hardware monitors

---

metricshub-doc/pom.xml

This pull request updates the Maven plugin version in the `metricshub-doc/pom.xml` file.
* Updated the `metricshub-connector-maven-plugin` version from `1.0.11` to `1.0.12` to ensure the project uses the latest plugin version. (`metricshub-doc/pom.xml`, [metricshub-doc/pom.xmlL122-R122](diffhunk://#diff-77ee4fa86779ba8e7a1d78405285cd8eafedbfc46b476339cb8c7d2d6a40b23aL122-R122))

Issue #722: Updated Connector Maven Plugin version to 1.0.12

---

metricshub-doc/pom.xml
metricshub-doc/src/site/markdown/custom/index.md
metricshub-doc/src/site/markdown/release-notes.md
pom.xml

- Bump enterprise version to 2.1.00 and otel to 0.127.0 in `pom.xml`
- Add release notes for MetricsHub Enterprise v2.1.00
- Document new features like JMX, REST API, and Informix JDBC driver
- Include updates for MetricsHub Community v1.0.04 and connectors
- Fix issues and update documentation for community edition
- Add support for Apache Cassandra and Palo Alto firewalls
This pull request introduces updates to the `metricshub-doc` project, including version upgrades and detailed release notes for various editions of MetricsHub. The most significant changes involve version updates in the `pom.xml` file and extensive documentation of new features, improvements, and fixes across different editions.
* [`metricshub-doc/pom.xml`](diffhunk://#diff-77ee4fa86779ba8e7a1d78405285cd8eafedbfc46b4763 …

Issue #717: Release notes for MetricsHub v2.1.00

---

metricshub-engine/src/main/java/org/metricshub/engine/common/helpers/KnownMonitorType.java
metricshub-engine/src/main/java/org/metricshub/engine/telemetry/Monitor.java
metricshub-engine/src/test/java/org/metricshub/engine/common/helpers/KnownMonitorTypeTest.java
metricshub-hardware/src/main/java/org/metricshub/hardware/strategy/HardwareMonitorNameGenerationStrategy.java

- Add `isConnector` method to `KnownMonitorType` and `Monitor` classes
- Update `HardwareMonitorNameGenerationStrategy` to filter endpoints
- Update `HardwareMonitorNameGenerationStrategy` to filter connector
- Enhance `KnownMonitorTypeTest` with `isConnector` test cases
- Refactor test assertions for better readability and clarity
- Use `var` for local variables in `computeIdCount` for conciseness
- Fix typos in comments for consistency and accuracy
---
This pull request introduces functionality to identify and handle "connector" monitor types, improves test coverage, and includes minor code refactoring for readability and consistency. The most significant changes are grouped below by theme.
* Added `isConnector` method to `KnownMonitorType` to determine if a given monitor type is a …

Issue #734: Fixed false positive error for missing `connector_id`

---

metricshub-doc/src/site/resources/css/site.css
metricshub-doc/src/site/site.xml

Massive changes in `site.css` to make the documentation render just like metricshub.com.

Updated site.xml and site.css to render doc just like metricshub.com

---

metricshub-agent/pom.xml
metricshub-agent/src/main/java/org/metricshub/agent/helper/AgentConstants.java
metricshub-agent/src/main/java/org/metricshub/cli/service/ApiKeyCliService.java
metricshub-agent/src/main/java/org/metricshub/web/MetricsHubAgentServer.java
metricshub-agent/src/main/java/org/metricshub/web/config/SecurityConfig.java
metricshub-agent/src/main/java/org/metricshub/web/security/ApiKeyAuthFilter.java
metricshub-agent/src/main/java/org/metricshub/web/security/ApiKeyRegistry.java
metricshub-agent/src/test/java/org/metricshub/web/security/ApiKeyAuthFilterTest.java
metricshub-agent/src/test/java/org/metricshub/web/security/ApiKeyRegistryTest.java
metricshub-doc/src/site/markdown/integrations/ai-agent-mcp.md

This pull request introduces API key-based authentication for the MetricsHub Agent, along with supporting infrastructure for managing and validating API keys. It also includes updates to the server configuration and tests to ensure the new functionality works as intended.
* Added `spring-boot-starter-security` dependency to enable Spring Security features (`metricshub-agent/pom.xml`).
* Implemented `ApiKeyAuthFilter` to authenticate requests using API keys provided in the `Authorization` header (`metricshub-agent/src/main/java/org/metricshub/web/security/ApiKeyAuthFilter.java`).
* Introduced `ApiKeyRegistry` for managing and validating API keys, including support for expiration dates (`metricshub-agent/src/main/java/org/metricshub/web/security/ApiKeyRegistry.java`).
* Created …

Issue #749: Added api key based authentication

---

pom.xml

Issue #762: Fixed devices configured with SNMPv3 AES cannot be monitored in MetricsHub Community Edition v1.0.06 

---

metricshub-agent/src/main/java/org/metricshub/agent/helper/ConfigHelper.java
metricshub-engine/src/main/java/org/metricshub/engine/configuration/HostConfiguration.java
metricshub-engine/src/main/java/org/metricshub/engine/strategy/source/SourceUpdaterProcessor.java
metricshub-engine/src/test/java/org/metricshub/engine/strategy/source/SourceUpdaterProcessorTest.java

* Updated ConfigHelper.java, HostConfiguration.java, SourceUpdaterProcessor.java, and SourceUpdaterProcessorTest.java

Issue #772: Ability to reference ${resource.attribute::ATTRIBUTE} where ATTRIBUTE is an attribute specified at the resource level (or above)
